version: "3.5"
services:
  database2:
    image: bitnami/mongodb:6.0
    container_name: mongodb
    environment:
      - MONGODB_ROOT_USER=admin
      - MONGODB_ROOT_PASSWORD=admin
      - MONGODB_USERNAME=quake
      - MONGODB_PASSWORD=quake
      - MONGODB_DATABASE=quakedb
    volumes:
      - ./data/mongodb:/bitnami/mongodb         # ./data - user owned. ./data/mongodb - sudo chown -R 1001 ./data/mongodb
    ports:
      - "27017:27017"
  database1:
    image: mysql:8
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: quakedb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
    ports:
      - "6033:3306"
    volumes:
      - ./data/sqldb:/var/lib/mysql