version: "3.5"
services:
  database2:
    image: bitnami/mongodb:6.0
    container_name: mongodb
    environment:
      - MONGODB_ROOT_USER=admin
      - MONGODB_ROOT_PASSWORD=admin
      - MONGODB_USERNAME=quake
      - MONGODB_PASSWORD=quake
      - MONGODB_DATABASE=quakedb
    volumes:
      - ./data/mongodb:/bitnami/mongodb         # ./data - user owned. ./data/mongodb - sudo chown -R 1001 ./data/mongodb
    ports:
      - "27017:27017"
  database1:
    image: postgres:12
    container_name: postgresdb
    environment:
      POSTGRES_DB: quakedb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbuser
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresdb:/var/lib/postgresql/data