micronaut:
  application:
    name: earthquakeMicronaut
mongodb:
  name: quakedb
  collection: quake
  uri: mongodb://quake:quake@localhost:27017/quakedb
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/quakedb
    driverClassName: org.postgresql.Driver
    db-type: postgresql
    username: dbuser
    password: dbuser
    dialect: org.hibernate.dialect.PostgreSQLDialect
r2dbc:
  datasources:
    rx-quake:
      url: r2dbc:postgresql://localhost:5432/quakedb
      username: dbuser
      password: dbuser
      schema-generate: NONE
      dialect: POSTGRES
jooq:
  datasources:
    default:
      sql-dialect: 'POSTGRES'
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
client:
  earthquake:
    url: https://earthquake.usgs.gov
