micronaut:
  application:
    name: earthquakeMicronaut
mongodb:
  uri: mongodb://quake:quake@localhost:27017/quakedb
datasources:
  default:
    url: jdbc:mysql://localhost:6033/quakedb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: dbuser
    password: dbuser
    dialect: org.hibernate.dialect.MySQL57Dialect
jooq:
  datasources:
    default:
      sql-dialect: 'MYSQL'
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
client:
  earthquake:
    url: https://earthquake.usgs.gov
