micronaut:
  application:
    name: earthquakeMicronaut
mongodb:
#  uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
  uri: mongodb://admin:admin@localhost:27017/quakedb
netty:
  default:
    allocator:
      max-order: 3
