micronaut:
  application:
    name: earthquakeMicronaut
mongodb:
  uri: mongodb://quake:quake@localhost:27017/quakedb
datasources:
  default:
    url: jdbc:mysql://localhost:6033/quakedb
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
    db-type: mysql
    username: dbuser
    password: dbuser
jooq:
  datasources:
    default:
      sql-dialect: 'MYSQL'
jpa:
  default:
    reactive: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        connection:
          url: ${datasources.default.url}
          username: ${datasources.default.username}
          password: ${datasources.default.password}
flyway:
  datasources:
    default:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
client:
  earthquake:
    url: https://earthquake.usgs.gov
vertx:
  mysql:
    client:
      port: 6033
      host: http://localhost
      database: quakedb
      user: ${datasources.default.username}
      password: ${datasources.default.password}
      maxSize: 5